config/routes.rb
Rails.application.routes.draw do
  get 'vehicles/new'

  get 'vehicles/show'

  get 'vehicles/edit'

  get 'vehicles/update'

  get 'vehicles/destroy'

  get 'vehicles/search'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/manage', to: 'static_pages#manage'
  patch '/take_vehicle', to: 'rentals#take_vehicle'
  patch '/return_vehicle', to: 'rentals#return_vehicle'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :vehicles
  resources :searches
  resources :rentals
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if @user = current_user
      @willRentals = current_user.rentals.where(["status LIKE ? ", 1])
      @rentals = current_user.rentals.where(["status LIKE ? ", 0])
      @pastRentals = current_user.rentals.where(["status LIKE ? ", -1])
      
      @vehicles = get_vehicle(@rentals)
      @willVehicles = get_vehicle(@willRentals)
      @pastVehicles = get_vehicle(@pastRentals)
    end
  end

  def help
  end

  def about
  end

  def contact
  end

  def manage
    if params[:search_user_id]
      if @user = User.find_by(id: params[:search_user_id])
        @rentals = @user.rentals.where(["status LIKE ? ", 0])
        @willRentals = @user.rentals.where(["status LIKE ? ", 1])
      else
        flash[:warning] = "Not found user"
      end
    end
    store_location
  end

  private
  def get_vehicle(rentals)
    vehicles = Array.new
    rentals.each do |b| 
      vehicles << Vehicle.find_by(id: b.vehicle_id)
    end      
    vehicles
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_mod.html.erb
<h1>Tất cả các yêu cầu</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nhãn hiệu</th>
      <th>Đời xe</th>
      <th>User</th>
      <th>Ngày nhận</th>
      <th>Ngày trả</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% get_request.each do |e| %>
      <tr>
        <td><%= Vehicle.find_by(id: e.vehicle_id).brand%></td>
        <td><%= Vehicle.find_by(id: e.vehicle_id).model %></td>
        <td><%= User.find_by(id: e.user_id).name %></td>
        <td><%= e.start_at %></td>
        <td><%= e.end_at %></td>
        <%= render 'shared/approve', object: e %>
        <%= render 'shared/deny',    object: e%>
      </tr>
    <% end %>
  </tbody>
</table>    

app/views/static_pages/_user.html.erb
<div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3>Yêu cầu thuê xe đã được chấp nhận</h3>
        <%= render @willVehicles %>
        <h3>Xe đang thuê</h3>
        <%= render @vehicles %>
        <h3>Lịch sử thuê xe</h3>
        <%= render @pastVehicles %>
      </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
    <h1>About</h1>
    <p>
      This is the capstone project for internship program at NovaHub.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact to HB 
  <a href="https://www.facebook.com/lethi.habinh">Facebook</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
    <h1>Help</h1>
    <p>
    0969280139
    </p>

app/views/static_pages/home.html.erb
<div class="col-md-3">
  <h4>Tìm kiếm hãng xe</h4>
  <%= form_tag vehicles_search_path, :method => 'get'  do %>
    <%= text_field_tag :search, params[:search]%>
    <%= submit_tag "Search" %>
  <% end %>
  <%= link_to("Tìm kiếm nâng cao", new_search_path ) %>
</div>

<div class="col-md-9">
  <% if logged_in? %>
    <% if current_user.mod? %>
      <%= render 'mod' %>
    <% else %>
      <%= render 'user' %>
    <% end %>
  <% else %>
  	<div class="center jumbotron">
  	  <h1> THUÊ XE CHẤT LƯỢNG, GIÁ CẢ HỢP LÝ </h1>

  	  <h2>ĐĂNG KÝ THÀNH VIÊN NGAY</h2>

  	  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  	</div>
  <% end %>
</div>

app/views/static_pages/manage.html.erb
<h2 class="text-center"></h3>

<%= form_tag manage_path, method: :get, class: 'form-inline' do %>
  <div class="form-group">
    <label>Nhập user id: </label>
    <div class="input-group">
      <input name="search_user_id" id="search_user_id" class="form-control" type="number">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Search</button>
<% end %>

<% unless @user.nil? %>
    <h3>User: <%= @user.name %></h3>
    <% if @willRentals.count == 0 %>
        <h4><%= @user.name %> không có bất kỳ yêu cầu nào đang chờ</h4>
    <% else %>
        <%= render 'shared/willRentals', object: @willRentals %>
    <% end %>
    <% if @rentals.count == 0 %>
        <h4><%= @user.name %> không có xe nào đang thuê</h4>
    <% else %>
        <%= render 'shared/rentals', object: @rentals %>
    <% end %>
<% end %>