config/routes.rb
Rails.application.routes.draw do
  get 'vehicles/new'

  get 'vehicles/show'

  get 'vehicles/edit'

  get 'vehicles/update'

  get 'vehicles/destroy'

  get 'vehicles/search'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/manage', to: 'static_pages#manage'
  patch '/take_vehicle', to: 'rentals#take_vehicle'
  patch '/return_vehicle', to: 'rentals#return_vehicle'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :vehicles
  resources :searches
  resources :rentals
end

app/views/shared/_approve.html.erb
<td>
  <%= form_for object, method: :patch do |f| %>
    <%= hidden_field_tag :verify, true %> 
    <%= hidden_field_tag :user_id, object.user_id %>
    <%= hidden_field_tag :vehicle_id, object.vehicle_id %>
    <%= f.submit "Approve", class: 'btn btn-primary' %>
  <% end %>
</td>

app/views/shared/_deny.html.erb
<td>
  <%= form_for object, method: :delete do |f| %>
    <%= hidden_field_tag :user_id, object.user_id %>
    <%= hidden_field_tag :vehicle_id, object.vehicle_id %>
    <%= f.submit "Deny", class: 'btn btn-warning' %>
  <% end %>
</td>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_rentals.html.erb
<h3>Xe đang thuê</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Tên xe</th>
      <th>Xác nhận</th>
    </tr>
  </thead>
  <tbody>
    <% object.each do |e| %>
      <tr>
        <td><%= Vehicle.find_by(id: e.vehicle_id).brand %> <%= Vehicle.find_by(id: e.vehicle_id).model %></td>
        <td>
          <%= form_tag return_vehicle_path, method: :patch do %>
            <%= hidden_field_tag :rental_id, e.id %>
            <%= submit_tag "Trả xe", class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>    

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>

app/views/shared/_willRentals.html.erb
<h3>Yêu cầu đang chờ</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Tên xe</th>
      <th>Xác nhận</th>
    </tr>
  </thead>
  <tbody>
    <% object.each do |e| %>
      <tr>
        <td><%= Vehicle.find_by(id: e.vehicle_id).brand %> <%= Vehicle.find_by(id: e.vehicle_id).model %></td>
        <td>
          <%= form_tag take_vehicle_path, method: :patch do  %>
            <%= hidden_field_tag :rental_id, e.id %>
            <%= submit_tag "Lấy xe", class: 'btn btn-primary' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>    