config/routes.rb
Rails.application.routes.draw do
  get 'vehicles/new'

  get 'vehicles/show'

  get 'vehicles/edit'

  get 'vehicles/update'

  get 'vehicles/destroy'

  get 'vehicles/search'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/manage', to: 'static_pages#manage'
  patch '/take_vehicle', to: 'rentals#take_vehicle'
  patch '/return_vehicle', to: 'rentals#return_vehicle'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :vehicles
  resources :searches
  resources :rentals
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
	has_many :rentals, dependent: :destroy
    # validates :name,  presence: true, length: { maximum: 100 }
	validate :start_end_date
	def start_end_date
		if start_at.present? && end_at.present? && start_at > end_at
			errors.add(:end_at, "Error datetime")		
		end
	end
	def self.search(search)
      if search
        where(["brand LIKE ?", "%#{search}%"])
      else
        all
      end
    end

    # def update_date
    #   update_columns(start_at: )
    # end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.paginate(page: params[:page])
  end

  def search
    @vehicles = Vehicle.search(params[:search]).paginate(page: params[:page])
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      flash[:succes] = "Successed"
      redirect_to 
    else 
      render 'new'
    end
  end

  def show
    session[:vehicle_id] = params[:id].to_i
    @vehicle = Vehicle.find(params[:id])
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.update_attributes(vehicle_params)
      flash[:success] = "Vehicle updated"
      redirect_to 
    else
      render 'edit'
    end
  end

  def destroy
    Vehicle.find(params[:id]).destroy
    flash[:succes] = "Vehicle deleted"
    redirect_to vehicles_url
  end

  private

    def vehicle_params
      params.require(:vehicle).permit(:isCar, :brand, :model, :price, :seat, :about)
    end

    

    
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
    def current_vehicle
        Vehicle.find(session[:vehicle_id])
    end
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <%= render 'shared/error_messages', object: @vehicle %>

 <%= f.label "Loại xe" %>
<select name="vehicle[isCar]">
  <option value="true">Ô tô</option>
  <option value="false">Xe máy</option>
</select>

 <%= f.label "Nhãn hiệu:" %>
  <%= f.text_field :brand, class: 'form-control' %>

 <%= f.label "Đời xe (Model):" %>
  <%= f.text_field :model, class: 'form-control' %>

 <%= f.label "Đơn giá: (/ngày)" %>
  <%= f.number_field :price, class: 'form-control' %>
  
 <%= f.label "Số chỗ ngồi:" %>
  <%= f.number_field :seat, class: 'form-control' %>
  
 <%= f.label "Chi tiết:" %>
  <%= f.text_area :about, class: 'form-control' %>


 <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/vehicles/_vehicle.html.erb
<li>
    <%= link_to vehicle.model, vehicle %> </br>
    <%= vehicle.brand%> </br>
    <%= vehicle.price%> Đồng / Ngày </br>
    <% if logged_in? %>
	    <% if current_user.mod? && !current_user?(@user) %>
		    <%= link_to "Xóa", vehicle, method: :delete, class: "btn btn-primary",
		                                  data: { confirm: "You sure?" } %>
		    <%= link_to "Cập nhật", edit_vehicle_path(vehicle), class: "btn btn-primary" %>
		<% end %>
	<% end %>
</li>

app/views/vehicles/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Cập nhật chi tiết xe</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/vehicles/index.html.erb
<% provide(:title, 'All vehicle') %>
<h1>Tất cả xe</h1>
<% if current_user.mod? && !current_user?(@user) %>
    <%= link_to "Thêm xe mới", new_vehicle_path, class: "btn btn-primary btn-lg" %>
<% end %>
<%= will_paginate %>

<ul class="vehicles">
    <%= render @vehicles %>
</ul>

<%= will_paginate %>

app/views/vehicles/new.html.erb
<% provide(:title, 'New Vehicle') %>
<% provide(:button_text, 'Lưu') %>
<h1>Thêm xe mới</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/vehicles/search.html.erb
<% provide(:title, 'Result') %>
<h1>Kết quả tìm kiếm</h1>

<%= will_paginate %>

<ul class="vehicles">
    <%= render @vehicles %>
</ul>

<%= will_paginate %>

app/views/vehicles/show.html.erb
<% provide(:title, @vehicle.model) %>
<h1>
   <%= @vehicle.model %>
</h1>
<div class="col-lg-6 col-md-6">
  <img src="http://thuexeotodanang.com.vn/data/thuexe/500/thue-xe-7-cho-fortuner-da-nang-1488991133.jpg">
</div>
<div class="vehicle col-lg-6 col-md-6">
	<h4>Nhãn hiệu</h4>
	<%= @vehicle.brand %>
	<h4>Đơn giá</h4>
	<%= @vehicle.price %> Đồng / Ngày
	<h4>Sô chỗ ngồi</h4>
	<%= @vehicle.seat %>
	<h4>Chi tiết</h4>
	<%= @vehicle.about %>	
</div>

<%= link_to("Đặt xe", new_rental_path(vehicle: @vehicle.id) , class: "btn btn-primary") %>